"""Billing routes."""
from flask import Blueprint, request
from config.db import get_db
from utils.helpers import success, error, token_required, role_required

bills_bp = Blueprint('bills', __name__)


@bills_bp.route('', methods=['POST'])
@token_required
@role_required('receptionist')
def create_bill(current_user):
    """POST /api/bills — Create a new bill for a completed appointment."""
    data = request.get_json(silent=True) or {}
    patient_id  = data.get('patient_id')
    doctor_id   = data.get('doctor_id')
    appointment_id = data.get('appointment_id')
    amount      = data.get('amount')
    details     = data.get('details') or ''

    if not all([patient_id, doctor_id, appointment_id, amount]):
        return error('patient_id, doctor_id, appointment_id and amount are required')

    try:
        amount = float(amount)
        if amount <= 0:
            return error('Amount must be positive')
    except (ValueError, TypeError):
        return error('Invalid amount')

    conn = get_db()
    cursor = conn.cursor(dictionary=True)
    try:
        # Check if appointment is completed
        cursor.execute("SELECT status FROM appointments WHERE id = %s AND patient_id = %s AND doctor_id = %s", 
                       (appointment_id, patient_id, doctor_id))
        appt = cursor.fetchone()
        if not appt:
            return error('Appointment not found', 404)
        if appt['status'] != 'completed':
            return error('Only completed appointments can be billed', 400)

        cursor.execute(
            """INSERT INTO bills (patient_id, doctor_id, appointment_id, amount, details)
               VALUES (%s, %s, %s, %s, %s)""",
            (patient_id, doctor_id, appointment_id, amount, details)
        )
        bill_id = cursor.lastrowid

        # Notify patient
        cursor.execute(
            "INSERT INTO notifications (user_id, message) VALUES (%s, %s)",
            (patient_id, f"Your bill of ₹{amount:.2f} has been generated by CityCare Hospital.")
        )
        conn.commit()
        return success({'bill_id': bill_id}, 'Bill created successfully', 201)
    except Exception as e:
        conn.rollback()
        return error(str(e), 500)
    finally:
        cursor.close()
        conn.close()


@bills_bp.route('', methods=['GET'])
@token_required
@role_required('receptionist', 'doctor')
def get_bills(current_user):
    """GET /api/bills — List all bills with patient and doctor names."""
    conn = get_db()
    cursor = conn.cursor(dictionary=True)
    try:
        cursor.execute("""
            SELECT b.*, u.name AS patient_name, u.email AS patient_email,
                   d.name AS doctor_name, d.specialization
            FROM bills b
            JOIN users u ON b.patient_id = u.id
            JOIN doctors d ON b.doctor_id = d.id
            ORDER BY b.created_at DESC
        """)
        bills = cursor.fetchall()
        for bill in bills:
            if bill.get('created_at'):
                bill['created_at'] = str(bill['created_at'])
            if bill.get('amount') is not None:
                bill['amount'] = float(bill['amount'])
        return success(bills)
    except Exception as e:
        return error(str(e), 500)
    finally:
        cursor.close()
        conn.close()


@bills_bp.route('/patient/<int:patient_id>', methods=['GET'])
@token_required
def get_patient_bills(patient_id, current_user):
    """GET /api/bills/patient/<id> — Bills for a specific patient."""
    if current_user['role'] == 'patient' and current_user['id'] != patient_id:
        return error('Forbidden', 403)

    conn = get_db()
    cursor = conn.cursor(dictionary=True)
    try:
        cursor.execute("""
            SELECT b.*, u.name AS patient_name,
                   d.name AS doctor_name, d.specialization
            FROM bills b
            JOIN users u ON b.patient_id = u.id
            JOIN doctors d ON b.doctor_id = d.id
            WHERE b.patient_id = %s
            ORDER BY b.created_at DESC
        """, (patient_id,))
        bills = cursor.fetchall()
        for bill in bills:
            if bill.get('created_at'):
                bill['created_at'] = str(bill['created_at'])
            if bill.get('amount') is not None:
                bill['amount'] = float(bill['amount'])
        return success(bills)
    except Exception as e:
        return error(str(e), 500)
    finally:
        cursor.close()
        conn.close()
